intel/compile-time-init-build

include/cib/detail/find.hpp, test/CMakeLists.txt, test/readme_hello_world.cpp
=> fix find_last_of when char isn't found

include/cib/detail/find.hpp, test/CMakeLists.txt, test/detail/type_to_string_view.cpp
=> fix cib::detail::name type string extraction algorithm

CMakeLists.txt, examples/CMakeLists.txt, examples/hello_world/CMakeLists.txt
Issue #117 is fixed with CPM adoption; this commit documents the example.
closes #117
=> :memo: Update example CMakeLists.txt

.clang-format, include/cib/top.hpp, include/container/Array.hpp, include/container/ConstexprMap.hpp, include/container/ConstexprSet.hpp, include/container/PriorityQueue.hpp, include/container/Vector.hpp, include/flow/detail/dependency.hpp, include/flow/detail/milestone_impl.hpp, include/flow/detail/parallel.hpp, include/flow/detail/walk.hpp, include/flow/impl.hpp, include/flow/milestone.hpp, include/log/catalog/mipi_encoder.hpp, include/log/fmt/logger.hpp, include/msg/handler.hpp, include/msg/match.hpp, include/seq/build_status.hpp, include/seq/builder.hpp, include/seq/detail/step_impl.hpp, include/seq/impl.hpp, include/seq/step.hpp, test/CMakeLists.txt, test/seq/sequencer.cpp
=> :sparkles: Add sequencer

include/cib/tuple.hpp, test/cib/tuple.cpp
`for_each` now supports:
- invocation on a const tuple or a mutable tuple -- it can mutate the tuple members (like std::for_each)
- returning the callable that was passed in (also like std::for_each)
- invocation as a free function to run a function over the expansion of several tuples
=> :white_check_mark: Add test for tuple for_each

include/cib/detail/nexus_details.hpp, include/cib/tuple.hpp, include/msg/field_matchers.hpp, include/msg/handler.hpp, include/msg/match.hpp, include/msg/message.hpp, test/cib/tuple.cpp
- Add unit tests for transform
- Extend transform to allow n-ary application (zip)
- Unify overloads of transform as for_each
=> :art: Improve tuple transform

include/cib/detail/compiler.hpp, include/log/catalog/mipi_encoder.hpp, test/CMakeLists.txt, test/log/mipi_encoder.cpp
Bind mipi log behaviour with tests; refactor mipi log code.
=> :white_check_mark: Add test for mipi log

include/sc/format.hpp, test/sc/format.cpp
Formatting allows integral types to be formatted, but not user-defined types that are convertible to integral types. Add a customization point "to_integral" which can be overloaded for user-defined types.
=> :bug: Allow formatting of user-defined integral types

.github/workflows/unit_tests.yml, CMakeLists.txt, cmake/sanitizers.cmake, cmake/test.cmake, test/log/logger.cpp
Add UBSan and ASan as a gating build for CI.
=> :hammer: Add sanitizer builds

include/cib/detail/nexus_details.hpp, include/cib/set.hpp, include/cib/tuple.hpp
Benchmark compilation improved by about 33%.
=> :zap: Speed up benchmark compilation

include/cib/config.hpp, include/cib/detail/conditional.hpp, test/cib/nexus.cpp
Rather than implementing a DSL, it seems easier to allow C++ to do the work. Obviates issue #21.
=> :recycle: Update conditional to use lambda

include/container/ConstexprMap.hpp, include/container/Vector.hpp, include/flow/milestone.hpp, include/log/catalog/mipi_encoder.hpp, include/log/fmt/logger.hpp, include/sc/detail/conversions.hpp, include/sc/detail/format_spec.hpp, include/sc/detail/string_meta.hpp, include/sc/format.hpp, include/sc/fwd.hpp, include/sc/lazy_string_format.hpp, include/sc/string_constant.hpp, include/seq/step.hpp, test/log/fmt_logger.cpp, test/sc/string_constant.cpp
- simplifications around container operations
- cleaning up various definitions of `operator==`
- removal of GCC <12 code
=> :recycle: Various refactorings

CMakeLists.txt
=> :bug: Use nm tool set by toolchain file

cmake/test.cmake
- clean up the handling of test libraries
- add rapidcheck
- remove non-working test discovery for gunit
=> :sparkles: Add rapidcheck for property-based tests

include/log/catalog/catalog.hpp, include/log/fmt/logger.hpp, test/log/mipi_encoder.cpp
GCC 13.1 complains about these.
=> :bug: Small fixes for includes/ambiguity

include/msg/field.hpp
First steps towards a better field design, re #261
=> Separate ideas of field_spec and field_locator

CMakeLists.txt, cmake/string_catalog.cmake, include/log/catalog/mipi_encoder.hpp, test/CMakeLists.txt, test/log/catalog_app.cpp, test/log/catalog_lib.cpp, test/log/mipi_encoder.cpp, tools/gen_str_catalog.py
Add a test to bind correct string catalog generation.
=> :bug: Fix string catalog generation

CODE_OF_CONDUCT.md, CONTRIBUTING.md
To match those in https://github.com/intel/safe-arithmetic
=> :page_facing_up: Update contribution guidelines and code of conduct

include/msg/callback.hpp, include/msg/disjoint_field.hpp, include/msg/field.hpp, include/msg/message.hpp
A little refactor to take advantage of the new match library in a more natural way, hopefully.
=> :art: Refactor field/message matchers to new structure

include/msg/callback.hpp, include/msg/handler.hpp
Collapse matchers into one instead of computing it in 3 places.
=> :art: Refactor msg callback

include/match/and.hpp, include/msg/detail/indexed_builder_common.hpp, include/msg/field_matchers.hpp, include/msg/indexed_builder.hpp, include/msg/indexed_callback.hpp, test/match/sum_of_products.cpp, test/msg/indexed_builder.cpp, test/msg/indexed_callback.cpp
Documentation to follow in a separate commit.
=> Fix not terms for indexed matchers/builder

test/interrupt/manager.cpp
It's not a callback, it's a mock. And it's not an IrqImpl, it's the test HAL.
=> :art: Tweaks to interrupt test

include/sc/detail/conversions.hpp, include/sc/detail/format_spec.hpp, include/sc/format.hpp
=> :bug: [cpp17] Fix string_view constructions with iterator and size

include/msg/callback.hpp, include/msg/indexed_callback.hpp
There was nothing particularly special about the `indexed_callback_t`.
=> :art: Refactor indexed_callback_t to use regular callback

CMakeLists.txt, include/msg/field.hpp, include/msg/field_matchers.hpp, include/msg/message.hpp
Also update stdx to bring in range concept and remove it from cib.
=> :bug: Make rel_matcher work on both message types and ranges

cmake/string_catalog.cmake, tools/gen_str_catalog.py
- use argparse
- add command line arguments for FIXME items
- separate reading the input and writing each output
=> :art: Refactor the gen_str_catalog python code

tools/gen_str_catalog.py
- Use generator comprehensions to read the file
- Eliminate global variable for string_id
- Use attributes in XML SubElement factory
=> :art: Improve gen_str_catalog

CMakeLists.txt, include/msg/field.hpp, include/msg/message.hpp
=> :arrow_up: Use `stdx::ct_capacity_v` in message/field calculations

cmake/string_catalog.cmake, test/CMakeLists.txt, test/log/catalog1_lib.cpp, test/log/catalog_app.cpp, test/log/stable_strings.json, tools/gen_str_catalog.py
=> :sparkles: Allow string catalog generation to use stable IDs

CMakeLists.txt, include/log/catalog/mipi_encoder.hpp, include/msg/message.hpp, test/log/mipi_encoder.cpp
=> :art: Use message library to define Mipi Sys-T messages

include/lookup/pseudo_pext_lookup.hpp, test/lookup/pseudo_pext_lookup.cpp
Fixed some integer conversion issues when using uint8_t keys.
=> tests and fixes for uint8_t lookups

.github/workflows/asciidoctor-ghpages.yml
Problem:
- The docs workflow does not build the docs the same way as the command line.
Solution:
- Use cmake to build the docs.
=> :bug: :books: Fix docs workflow

docs/message.adoc
This just fixes a typo in the message documentation
=> :books: :bug: Fix combining messages example

include/flow/graphviz_builder.hpp, include/log/catalog/builder.hpp
Problem:
- Two headers are missing `#pragma once`.
Solution:
- Add it.
=> :bug: Add missing `#pragma once` directives
