intel/compile-time-init-build

- include/cib/nexus.hpp
> workaround bugs in clang and gcc to optimize compiled efficiency

- include/cib/detail/set_details.hpp
- include/flow/milestone.hpp
Immediate (consteval) functions can't be called from constexpr functions. There is no reason for create_type_names not to be an immediate function, I think.
Note: re https://github.com/intel/compile-time-init-build/issues/27, I think this is related. The reason tests don't compile properly under GCC 11.2 (and now 12.2) is likely that consteval functions are being called from constexpr functions (or lambdas, which is the same thing). See also https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95968 - lambdas are implicitly constexpr (if they can be) but not implicitly immediate. I don't think this is a GCC bug.
With this change, all tests compile with GCC 12.2 except nexus.cpp and flow.cpp, which both run into the constexpr/consteval issue related to tuple handling.
The Array test compiles but …
> Fix create_type_names for GCC 12.2

- include/cib/tuple.hpp
Remove multiple `tuple_element` specializations for indexing with types; replace it with a CRTP mixin that allows indexing with types in a parameter pack.
> Use CRTP for type-based tuple indexing

- CMakeLists.txt
The release_header target had incorrectly specified dependencies. Changed it to properly depend on all headers and to make the required directory at build time rather than generate time.
> :bug: Fix release_header target

- .github/workflows/unit_tests.yml
- include/cib/detail/components.hpp
- include/cib/detail/conditional.hpp
- include/cib/detail/config_details.hpp
- include/cib/detail/config_item.hpp
- include/cib/detail/exports.hpp
- include/cib/detail/extend.hpp
- test/container/Array.cpp
GCC 11 correctly points out that the following cannot be compiled:
```cpp
struct S {
int i{42};
consteval auto func() { return i; }
};
constexpr auto call_func_on(auto obj) {
return obj.func();
}
constexpr S s;
constexpr auto x = call_func_on(s);
```
Even though `s` is `constexpr`, inside `call_func_on` it's a parameter, and there's no such thing as constexpr function parameters in C++. So attempting to call a `consteval` function fails. When func is `constexpr`, everything is OK.
GCC 11 also correctly spots that indexing into a C-style array of size 0 is UB, so that test is changed to merely declaring an array of size 0. TBD: `Array<T, 0>` should simply not support many operations. See [what the standard says about `std::array<T, 0>`](http://eel.is/c++draft/array.zero).
> :bug: Fix constexpr evaluation for GCC 11

- include/interrupt/dynamic_controller.hpp
- include/interrupt/manager.hpp
- test/conc/concurrency.hpp
- test/interrupt/manager.cpp
It's better to pass a policy as a template argument than rely on a global dependency.
> :art: Inject ConcurrencyPolicy into dynamic_controller

- cmake/dependencies.cmake
Older versions of git apparently don't support `git tag --points-at <hash>` - they need to be told `git tag -l --points-at <hash>`.
> :bug: Fix git tag usage

- benchmark/CMakeLists.txt
- include/cib/tuple.hpp
- test/cib/tuple.cpp
In this commit:
- testing tuple type_traits
- compile-time tests as well as runtime tests
- value category tests
- added tests for apply and fold
> :recycle: :white_check_mark: Refactor and add tests for tuple

- .github/workflows/unit_tests.yml
- Remove support for clang 7 & 8 -- they have problems with some constexpr constructs that will be hard to support in future.
- Use Ninja for CI builds -- this shaves about 2 minutes off the quality build.
- Rework build matrix to support all desired combinations: compilers, compiler versions, C++ standards, build type (for now only Debug).
- `single_header` builds are removed for now because they don't actually make a difference? We don't have tests that include `cib/cib.hpp` as a unified header.
Note: ubuntu-latest is currently 20.04, NOT 22.04 yet. Hence GCC 12+ and Clang 15+ are not available without moving forward either by updating to ubuntu-22.04 or when github updates ubuntu-latest to 22.04.
> :construction_worker: Use Ninja for CI, rework build matrix

- .github/workflows/unit_tests.yml
- CMakeLists.txt
- README.md
- benchmark/CMakeLists.txt
- cmake/clang-tidy.cmake
- cmake/test.cmake
- include/cib/detail/set_details.hpp
- include/seq/step.hpp
- test/CMakeLists.txt
In this commit:
- Unit tests are separated by subsystem and more easily declared.
- The `all` target is cleaned up so as not to include building the release header or compilation benchmark.
- Unit tests run as part of the build rather than a separate step.
Also:
- This PR includes a fix for seq/step.hpp which for some reason tools were not flagging before?
- clang-tidy in LLVM 11.0.0 has a bug that (only sometimes) gives a false positive on comparisons - worked around in cib/detail/set_details.hpp.
> :white_check_mark: Structure units tests better

- include/cib/callback.hpp
- include/cib/config.hpp
- include/cib/detail/builder_traits.hpp
- include/cib/detail/compiler.hpp
- include/cib/detail/components.hpp
- include/cib/detail/conditional.hpp
- include/cib/detail/config_details.hpp
- include/cib/detail/config_item.hpp
- include/cib/detail/exports.hpp
- include/cib/detail/extend.hpp
- include/cib/detail/meta.hpp
- include/cib/detail/nexus_details.hpp
- include/cib/detail/set_details.hpp
- include/cib/nexus.hpp
- include/cib/tuple.hpp
We target C++17 and above; `CIB_CONSTEXPR` is never anything other than `constexpr`. `constexpr` is already used a lot and we might as well use the standard keyword everywhere.
This commit also cleans up the include usage for `cib/details/compiler.hpp`.
> :art: Remove CIB_CONSTEXPR

- CMakeLists.txt
- include/log/fmt/logger.hpp
Linking against `fmt::fmt` causes projects that depend on cib to build the non-header parts of libfmt, which cib doesn't use. Better to link against `fmt::fmt-header-only`.
> :bug: Use libfmt in header-only mode

- .github/workflows/performance_test.yml
- .github/workflows/release.yml
- .github/workflows/unit_tests.yml
Github just updated ubuntu-latest to 22.04, resulting in package availability changes that broke the CI. Pinning to 20.04 until we are ready to go to 22.04.
> :hammer: Pin CI images to ubuntu 20.04

- include/log/catalog/mipi_encoder.hpp
`make_short32_header` is a `constexpr` function but cannot be a `consteval` function.
> :bug: Fix make_short32_header

- include/log/fmt/logger.hpp
- test/CMakeLists.txt
- test/log/logger.cpp
- test/log/testing_logger.hpp
fmt::format returns a string which uses dynamic memory so every trace and log produced small dynamic memory allocations switch to use fmt::format_to with fmt::memory_buffer thsize can be set with changing fmt::internal::INLINE_BUFFER_SIZE
closes#221
> Fix Logger uses dynamic memory (std::string)

- .github/workflows/performance_test.yml
- .github/workflows/unit_tests.yml
Merges can be gated on the success of a job, but when using a matrix, it's annoying to put in all the variants as gating. This commit adds a merge_ok job that depends on both the unit tests and the quality checks passing.
Also:
- Cancel in progress jobs that are superseded (for example by pushing newer code to a branch on a PR).
- Fix workflow name of the performance tests.
> :green_heart: Fix merge gating

- include/log/fmt/logger.hpp
`high_resolution_clock` sounds good but doesn't deliver: it's not well-defined by the standard. In libc++ and MS STL it is an alias for `steady_clock`; however in libstdc++ it is an alias for `system_clock` (which is not steady).
As a rule of thumb, `high_resolution_clock` should never be used. For a stopwatch, use `steady_clock`. For a wall time, use `system_clock`.
https://stackoverflow.com/a/38253266
> :art: Use steady_clock instead of high_resolution_clock

- include/msg/match.hpp
- test/msg/handler.cpp
The way that tuple filter works currently requires the elements of the tuple to be default constructible. This was not the case for `any_t`.
This is a partial fix for #231 (which is two issues in one).
> :bug: Fix message handler with multiple callbacks

- include/sc/fwd.hpp
- test/sc/format.cpp
`sc::type_` does not need to instantiate the type to represent its name.
> :bug: Allow logging names of incomplete types

- .clang-format
- include/log/fmt/logger.hpp
`fmt::format_to` does not null-terminate the output. The fmt logging code assumed that the data in the fmt::memory_buffer was null-terminated, resulting in printing garbage characters sometimes.
> :bug: Fix fmt logger reading off end of buffer

- include/cib/tuple.hpp
- include/msg/match.hpp
- test/msg/match.cpp
`any_t` and `all_t` do the same thing, just with different monoids. The match test defined its own `always`, but this is available from the header.
> :art: DRY out match::any and match::all

- include/cib/detail/compiler.hpp
- tools/gen_str_catalog.py
- `log_level` -> `logging::level`
- including `log/log.hpp` instead of `log/log_levels.hpp`
> :bug: Fix gen_str_catalog for new logging

- include/log/log.hpp
- test/log/fmt_logger.cpp
- test/log/log.cpp
`logging::config` should be declared `inline` so that it doesn't provoke link errors.
> :bug: Make logging::config an inline variable template

- include/container/ConstexprSet.hpp
- include/container/Vector.hpp
- test/container/ConstexprMap.cpp
- test/container/ConstexprMultiMap.cpp
- test/container/ConstexprSet.cpp
- test/container/Vector.cpp
- test/container/log.hpp
- Use CHECK and REQUIRES properly: REQUIRES halts a test if it cannot continue and should be used before operations that will otherwise be UB, e.g. REQUIRE an index is in range before using it.
- Add tests for the CIB_ASSERT or CIB_FATAL control paths in container usage, now that that behaviour can be injected with a log config.
> :recycle: :white_check_mark: Refactor container tests

- include/log/catalog/mipi_encoder.hpp
- include/log/fmt/logger.hpp
- include/log/log.hpp
- test/log/fmt_logger.cpp
- test/log/mipi_encoder.cpp
Using fmt for logging implies including some parts of the STL like iostreams; if a client doesn't want to use fmt for logging this should not be pulled in.
> :art: Make log implementations opt-in

- .github/workflows/performance_test.yml
- .github/workflows/unit_tests.yml
- benchmark/CMakeLists.txt
The perf test does not fail the job when it fails. It also uses deprecated github commands.
Closes #205
> :construction_worker: Fix performance test

- CMakeLists.txt
The `sanitize` target is internal and shouldn't use the name for dependents of the cib library.
> :construction_worker: Don't expose sanitize target

- CMakeLists.txt
If clang-tidy is not available, it should not prevent local development.
> :construction_worker: Make clang-tidy optional

- .github/workflows/performance_test.yml
- .github/workflows/release.yml
- .github/workflows/unit_tests.yml
- CMakeLists.txt
- include/cib/detail/nexus_details.hpp
- include/cib/detail/type_list.hpp
- include/cib/detail/type_pack_element.hpp
- include/cib/tuple.hpp
- include/container/Vector.hpp
- include/flow/impl.hpp
- include/flow/milestone.hpp
- include/flow/run.hpp
- include/interrupt/config/fwd.hpp
- include/interrupt/dynamic_controller.hpp
- include/interrupt/fwd.hpp
- include/interrupt/manager_interface.hpp
- include/msg/handler.hpp
- include/sc/format.hpp
- include/seq/step.hpp
- test/sc/format.cpp
- test/sc/string_constant.cpp
- clang/GCC 9 and 10 are now considered "older compilers" and only build C++17
- updated clang-format has reformatted some files.
- updated clang-tidy: tweaked Vector.hpp to use `std::array<...>::data`.
- updated clang-tidy: nolint directives for abstract base classes that don't define a virtual destructor (`flow::interface` and `interrupt::manager_interface`).
> :construction_worker: Update CI: add llvm-15, use ubuntu-22.04

- tools/gen_str_catalog.py
The argument parsing for string catalog generation was confused by commas appearing in types (template instantiations).
Python has also been reformatted with black.
> :bug: Fix string catalog type parsing

- CMakeLists.txt
When used by another project, CIB's include directory is wrong.
> :bug: Fix include directory

- include/cib/detail/nexus_details.hpp
- include/cib/nexus.hpp
> :recycle: Simplify expression of `initialized_builders`

- .github/workflows/unit_tests.yml
- .gitignore
- CMakeLists.txt
- cmake/clang-tidy.cmake
- cmake/quality.cmake
- cmake/sanitizers.cmake
- cmake/test.cmake
- don't download test frameworks if they are not used
- provide dummy clang-tidy targets when not using clang toolchain
> :recycle: Refactor cmake infrastructure

- include/cib/top.hpp
Providing access to services through a variable template causes the clang frontend to ICE. Providing access through a function is apparently fine.
> :bug: Workaround for clang ICE

- include/cib/tuple.hpp
- test/conc/concurrency.hpp
Nothing currently uses the overload that takes a predicate; it's easier if the predicate (if any) is the second argument.
> :recycle: Refactor `ConcurrencyPolicy`

- tools/gen_str_catalog.py
The regex was not matching `cib::tuple` correctly.
> :bug: Fix string catalog generation

- .github/workflows/performance_test.yml
- .gitignore
Create a set summary for the performance_test action which displays in the GitHub action screen.
Summarize the Clang front end time, and expand out to provide the compilation timing log.
> Show summary for performance test action output

- include/container/ConstexprMap.hpp
- include/container/ConstexprMultiMap.hpp
- include/container/Vector.hpp
- include/flow/builder.hpp
- include/msg/message.hpp
- include/sc/detail/string_meta.hpp
- include/sc/format.hpp
- include/seq/builder.hpp
Update to use C++20 constexpr std algorithms
- update code tagged to be rewritten after updating to C++20.
- convert Vector to use C++20 algorithms
- convert message to use C++20 algorithms
- convert sc/format to C++20 algorithms
The change to `flow::generic_builder::hasNoIncomingEdges()` resulted in
a build failure in GCC, but success in Clang. This was tracked down to
the `begin()` and `end()` iterators some how resulting in a different
type in GCC. This then caused GCC's implementation to fail when it
attempted to subtract the iterators.
This was fixed by always using the `std::{c}begin()` method to generate
both the begin and end iterators. Other occurrences of the generation of
end iterators in a similar way were identified and corrected in
`Vector`.
> C++20 cleanup to use `constexpr` STL algorithms

- .github/workflows/unit_tests.yml
- cmake/sanitizers.cmake
Use a matrix to build sanitized tests using UBSan, ASan and TSan.
> :construction_worker: Split sanitizer checks

- tools/gen_release_header.py
The release header now is rendered with all non-cib headers collected and sorted at the top of the file.
This prevents including the standard library headers multiple times.
> Group and sort includes in release header

- include/cib/tuple.hpp
- include/cib/tuple_destructure.hpp
- test/cib/tuple.cpp
Destructuring is in a separate header to avoid otherwise unwarranted inclusion of `<tuple>`.
Closes #307
> :sparkles: Add ability to destructure cib::tuple

- include/cib/tuple.hpp
- include/cib/tuple_destructure.hpp
- test/cib/tuple.cpp
On GCC, `cib::tuple<Ts...>` was an alias for `cib::tuple_impl<X, Y, Ts...>` which meant that type-based concat of `cib::tuple` didn't work. e.g.
```cpp
using T = boost::mp11::mp_append<cib::tuple<int>,
cib::tuple<float>>;
```
This was different on clang because clang doesn't support template alias deduction guides yet. But it's easier all round if it's the same on both compilers, and an actual type so that type-based concatenation works.
> :bug: Fix type-based concatenation for cib::tuple

- .clang-format
- cmake/test.cmake
Linking against the test-framework-specific rapidcheck libraries pulls in the base rapidcheck library without marking it as a system dependency, which means warnings leak.
> :bug: Fix rapidcheck linking as a system library

- include/container/vector.hpp
- include/msg/message.hpp
- test/container/vector.cpp
- test/msg/message.cpp
There are several use cases where `resize_and_overwrite` is a useful function for message data. With static capacity, the interface is not quite the same as on `std::string`, hence it's a free function. But `resize_and_overwrite` is still a good name, because that's what it does.
Also, simplify constructors for message_base.
> :new: Add resize_and_overwrite for vector

- include/msg/message.hpp
- test/msg/message.cpp
Accept a range of T as a constructor argument for `message_base`, where T is convertible to `std::uint32_t`.
This unblocks issue #315.
TODO: properly relax the value type of `message_base`'s storage, as discussed with @mjcaisse-intel.
> :adhesive_bandage: Relax message_base range constructor constraints

- include/msg/field.hpp
- include/msg/message.hpp
- test/msg/handler.cpp
- test/msg/handler_builder.cpp
- test/msg/message.cpp
`message_base` size was not set correctly when constructing from a range or a variadic pack of integral types.
Remove message_base NumDWords template parameter: there was no need for it.
Closes #317
> :bug: :boom: Fix message_base size

- include/msg/disjoint_field.hpp
- test/msg/message.cpp
Add `MaxDWordExtent` member to `disjoint_field` to fulfill the requirement introduced by #320.
Add `ValueType` alias to `disjoint_field`.
> Fix disjoint_field use in message

- CMakeLists.txt
- include/msg/detail/func_traits.hpp
The `FindPythonInterp` module was deprecated in cmake 3.12 and removed in cmake 3.27. It was replaced by `FindPython3` and friends.
See output of: `$ cmake --help-policy CMP0148`
> :alien: Update how cmake finds python

- CMakeLists.txt
- include/sc/format.hpp
This fix enables a cleaner way to format at compile time.
> :arrow_up: Update fmtlib for constexpr fix to `formatted_size`

- include/cib/tuple_algorithms.hpp
Compilation benchmark performance regressed in #323 - this fixes the regression.
> :zap: Speed up tuple `contains_type`

- include/flow/graph_builder.hpp
- include/flow/impl.hpp
- include/seq/impl.hpp
- test/flow/flow.cpp
- test/seq/sequencer.cpp
Building flows/sequences was not safe without right-sizing the output structure. Now it is safe:
- asserts when providing a structure that's too small
- uses only the initialized storage when providing a structure that's larger than necessary
Removed some duplicated seq tests and unused (/only test-supporting) seq constructors.
> :recycle: Flow building: tidy up and make safer

- include/log/catalog/catalog.hpp
- include/log/catalog/mipi_encoder.hpp
- tools/gen_str_catalog.py
The types used to encode messages for overload in the catalog don't need to be instantiable. This simplifies what `strings.cpp` needs to include, and what the generation script needs to handle.
> :art: Simplify message catalog types

- include/msg/handler_interface.hpp
- include/msg/indexed_builder.hpp
- test/msg/handler_builder.cpp
- test/msg/indexed_builder.cpp
If a message matches on indexed fields, but doesn't match the full matcher in the callback, the callback shouldn't be called.
> :bug: Fix issue #370

- .github/workflows/asciidoctor-ghpages.yml
Added conditional check for the GitHub pages build to prevent the steps and jobs that interact with GitHub pages from running on any forked copy.
The actual documentation build step is still executed, just no publishing steps.
This caused an issue when I updated my fork because it would crash out trying to setup the GitHub pages, and then when I enabled that it would publish to my personal site, so I have disabled the publishing steps for all forks.
It might be possible to move the `Setup GitHub Pages` step up into the `configure` job, but not sure if that makes sense as I've not used these actions before.
> :construction_worker: Prevent publish GitHub Pages on Forks

- .github/workflows/asciidoctor-ghpages.yml
- .github/workflows/performance_test.yml
- .github/workflows/release.yml
- .github/workflows/single_header.yml
- .github/workflows/unit_tests.yml
When a contributor forks the repository, it is not possible to use the Intel runners.
Detect the repository owner and only use the Intel runners when the workflow is running from the Intel repository.
> :construction: Forks build on GitHub hosted Runners

- CMakeLists.txt
- include/msg/detail/indexed_builder_common.hpp
- include/msg/detail/indexed_handler_common.hpp
- include/msg/detail/rle_codec.hpp
- include/msg/indexed_builder.hpp
- include/msg/indexed_handler.hpp
- include/msg/rle_indexed_builder.hpp
- include/msg/rle_indexed_handler.hpp
- include/msg/rle_indexed_service.hpp
- test/CMakeLists.txt
- test/msg/detail/rle_codec.cpp
- test/msg/rle_indexed_builder.cpp
I have implemented a `rle_indexed_service` and `rle_indexed_builder` to provide a RLE blob version of the existing ones. 
This provides a compressed message field index lookup mechanism to reduce overall storage requirements, especially on large indices.
> :microscope: run length encoded indexed message handling

- include/msg/detail/indexed_builder_common.hpp
- include/msg/indexed_callback.hpp
- test/msg/indexed_builder.cpp
Indexed builder was handling callback matchers correctly but failing to account for matchers in the message fields themselves.
> :bug: Take account of message/field matchers in indexed handler

- include/msg/detail/indexed_builder_common.hpp
- include/msg/indexed_callback.hpp
- include/msg/message.hpp
- test/CMakeLists.txt
- test/msg/impossible_match_callback.cpp
- test/msg/impossible_match_field.cpp
- test/msg/indexed_builder.cpp
When it's not possible to match a callback, it could be an error. It might not be, depending on config. So this is controlled with an injectable config.
> :sparkles: Add error when callback matchers reduce to `never`

- include/msg/field.hpp
- include/msg/message.hpp
- test/msg/field.cpp
A followup to #408 - field locators don't have to specify a dword index, they can just use msb/lsb.
> Binary at for field locators

- CMakeLists.txt
- docs/message.adoc
- include/msg/callback.hpp
- include/msg/detail/indexed_builder_common.hpp
- include/msg/detail/indexed_handler_common.hpp
- include/msg/field.hpp
- include/msg/field_matchers.hpp
- include/msg/message.hpp
- test/CMakeLists.txt
- test/msg/callback.cpp
- test/msg/fail/impossible_match_callback.cpp
- test/msg/fail/impossible_match_field.cpp
- test/msg/handler.cpp
- test/msg/handler_builder.cpp
- test/msg/indexed_builder.cpp
- test/msg/indexed_handler.cpp
- test/msg/message.cpp
- test/msg/rle_indexed_builder.cpp
Messages are reworked:
- separate definition from storage
- owning, mutable view and const view types
- construction from arrays and/or by setting fields
- get and set fields by name
Handlers, matchers and callbacks don't incur any copying any more; message views
can be constructed cheaply over raw arrays.
Closes: #315
Closes: #394
Closes: #395
Closes: #398
> :art: :recycle: Refactor messages

- include/interrupt/config/fwd.hpp
- include/interrupt/config/irq.hpp
- include/interrupt/config/root.hpp
- include/interrupt/config/shared_irq.hpp
- include/interrupt/config/shared_sub_irq.hpp
- include/interrupt/config/sub_irq.hpp
- include/interrupt/impl/irq_impl.hpp
- include/interrupt/impl/shared_irq_impl.hpp
- include/interrupt/impl/shared_sub_irq_impl.hpp
- include/interrupt/policies.hpp
- include/match/implies.hpp
- test/interrupt/manager.cpp
- simplify `implies`
- remove a header that contained Yet Another typedef for pointer-to-function-returning-void
- remove an unused header from a test
- use conventional type spellings
> Small cleanups

- include/interrupt/config/irq.hpp
- include/interrupt/config/root.hpp
- include/interrupt/config/shared_irq.hpp
- include/interrupt/config/shared_sub_irq.hpp
- include/interrupt/config/sub_irq.hpp
- include/interrupt/hal.hpp
- include/interrupt/impl/irq_impl.hpp
- include/interrupt/impl/manager_impl.hpp
- include/interrupt/impl/shared_irq_impl.hpp
- include/interrupt/impl/shared_sub_irq_impl.hpp
- include/interrupt/impl/sub_irq_impl.hpp
- include/interrupt/manager.hpp
- include/interrupt/policies.hpp
- test/interrupt/manager.cpp
Carrying the (global) interrupt HAL dependency through all the interrupt types is an artifact; this change injects it.
> :art: Inject the interrupt HAL

- examples/flow_daily_routine/main.cpp
- include/flow/README.md
- include/flow/builder.hpp
- include/flow/graph_builder.hpp
- include/flow/impl.hpp
- include/flow/milestone.hpp
- include/interrupt/builder/irq_builder.hpp
- include/interrupt/builder/sub_irq_builder.hpp
- include/interrupt/manager.hpp
- include/match/and.hpp
- include/match/bin_op.hpp
- include/match/or.hpp
- include/msg/callback.hpp
- include/msg/detail/indexed_builder_common.hpp
- include/msg/indexed_callback.hpp
- include/seq/builder.hpp
- include/seq/impl.hpp
- test/flow/flow.cpp
- test/interrupt/manager.cpp
- test/msg/callback.cpp
- test/msg/fail/impossible_match_callback.cpp
- test/msg/fail/impossible_match_field.cpp
- test/msg/handler.cpp
- test/msg/handler_builder.cpp
- test/msg/indexed_builder.cpp
- test/msg/indexed_callback.cpp
- test/msg/rle_indexed_builder.cpp
With C++20, we can pass strings as NTTPs directly and we don't need to say `decltype("hello"_sc)` everywhere.
> :art: Remove clumsy decltyping of string constants

- include/interrupt/builder/irq_builder.hpp
- include/interrupt/builder/shared_irq_builder.hpp
- include/interrupt/builder/shared_sub_irq_builder.hpp
- include/interrupt/builder/sub_irq_builder.hpp
- include/interrupt/config/irq.hpp
- include/interrupt/config/root.hpp
- include/interrupt/config/shared_irq.hpp
- include/interrupt/config/shared_sub_irq.hpp
- include/interrupt/config/sub_irq.hpp
- include/interrupt/dynamic_controller.hpp
- include/interrupt/fwd.hpp
- include/interrupt/hal.hpp
- include/interrupt/impl/irq_impl.hpp
- include/interrupt/impl/manager_impl.hpp
- include/interrupt/impl/shared_irq_impl.hpp
- include/interrupt/impl/shared_sub_irq_impl.hpp
- include/interrupt/impl/sub_irq_impl.hpp
- test/interrupt/common.hpp
- test/interrupt/dynamic_controller.cpp
- test/interrupt/manager.cpp
- separate dynamic tests from manager tests
- add strong type for irq number so as not to mix up with priority
- conventional names for types
> :art: Clean up interrupt lib

- CMakeLists.txt
We were previously on a between-release commit in order to support constexpr `formatted_size` calls.
> :arrow_up: Update to fmtlib 10.1.1

- CMakeLists.txt
CIB uses libfmt in header-only mode, so we should turn off the `FMT_OS` option. And the `FMT_INSTALL` option to boot.
> :bug: Turn off `FMT_OS` option for libfmt

- include/flow/builder.hpp
- include/flow/detail/par.hpp
- include/flow/detail/seq.hpp
- include/flow/detail/walk.hpp
- include/flow/graph_builder.hpp
- include/seq/builder.hpp
- test/flow/flow.cpp
- test/seq/sequencer.cpp
- use `tag_invoke` to walk the flow node tree; this will enable using other types in the flow tree if needed (thinking of #278)
- remove CRTP from graph_builder; it's not needed
- convert flow tests to use the "builder pattern" - in general, `add` functions that can return different types should be marked `[[nodiscard]]`? (Not yet true for `graph_builder`, but moving that way.)
> Decouple graph builder

- include/msg/field.hpp
- test/msg/field_extract.cpp
- test/msg/field_insert.cpp
When an argument to any binary operator is an integral type with width less than `int`, integer promotion rules mean that the result is an `int`. Even when the types involved are unsigned...
> :bug: Fix accidental integer promotion in field type handling

- docs/message.adoc
- test/msg/field_extract.cpp
- test/msg/field_insert.cpp
More significant parts come first.
> :white_check_mark: Clarify the ordering of `at` arguments in a field

- docs/match.adoc
- include/match/ops.hpp
- test/match/equivalence.cpp
Further research indicates that we had it the wrong way around.
> Fix matcher ordering

- include/msg/callback.hpp
- include/msg/indexed_callback.hpp
- test/msg/handler_builder.cpp
- test/msg/indexed_builder.cpp
- test/msg/indexed_handler.cpp
This was supported by regular callbacks, but untested and incomplete for indexed callbacks.
> :art: Allow indexed callbacks to handle extra arguments

- include/msg/field.hpp
- include/msg/field_matchers.hpp
- test/msg/callback.cpp
- test/msg/field_matchers.cpp
- test/msg/handler.cpp
- test/msg/handler_builder.cpp
The field spec already knows its type, so a matcher doesn't need to be told both the field spec and the type.
> :art: Remove unnecessary type specifier for field matcher

- include/msg/message.hpp
- test/msg/callback.cpp
I'm finding the current API for msg callback matchers being too verbose. This PR provides a simpler option.
> add convenience msg matcher

- include/msg/detail/indexed_builder_common.hpp
GCC 13.2 complains about using a glvalue in a constant expression.
> :bug: Fix constexpr glvalue usage

- cmake/string_catalog.cmake
- include/sc/format.hpp
- include/sc/string_constant.hpp
- test/CMakeLists.txt
- test/log/catalog2_lib.cpp
- test/log/catalog_app.cpp
- test/log/catalog_enums.hpp
- tools/gen_str_catalog.py
For example, in order to format enums at runtime, the types need to be defined.
> :sparkles: Support extra headers for generated strings TU

- include/log/catalog/catalog.hpp
- include/log/catalog/mipi_encoder.hpp
- include/log/fmt/logger.hpp
- include/log/log.hpp
- test/CMakeLists.txt
- test/log/catalog1_lib.cpp
- test/log/catalog2_lib.cpp
- test/log/fmt_logger.cpp
- test/log/mipi_encoder.cpp
- test/log/module_id.cpp
- tools/gen_str_catalog.py
A module ID is a compile-time string. Module ID is overridden in the current scope with the `CIB_LOG_MODULE` macro. Module IDs are mapped in the same way as string catalog IDs, with a link-time dependency.
> :sparkles: Add module ID to logs

- .github/workflows/unit_tests.yml
Problem:
- clang-tidy takes a long time in CI
Solution:
- Only clang-tidy the files that are changed in a PR.
> :construction_worker: Clang-tidy changed files in CI

- CMakeLists.txt
- include/msg/field.hpp
Simplified `bits_locator_t::insert` a little: two compile-time cases can be collapsed into one.
> :art: Refactor field to use stdx::bit_mask

- cmake/string_catalog.cmake
- test/CMakeLists.txt
If the `OUTPUT_LIB` argument is omitted, a library target will not be generated. The caller can generate their own library that builds the cpp file they specified.
Closes #515
> :art: Optional generation of the string catalog library

- include/interrupt/fwd.hpp
- include/msg/field.hpp
- include/msg/message.hpp
- include/sc/fwd.hpp
In particular `msg::literals` receives the `_field` and `_f` UDLs. Also `_sc::literals` gets the `_sc` UDL.
Note: `_sc` is currently exposed in the global namespace... it's a TODO to make that better and maybe use `_cts` from `stdx`.
> :art: Put UDLs inside `literals` namespaces

- README.md
'"' was missing in the markdown
Looked weird
> docs(README.md): fix typo in CPM section

- docs/message.adoc
- include/msg/field.hpp
- include/msg/message.hpp
- test/msg/message.cpp
- Sort message fields by lsb
- Allow message extension
> :sparkles: Add `msg::extend`

- tools/gen_str_catalog.py
Problem:
- Python regular expressions contain invalid escape sequences.
- In Python 3.12, invalid escape sequences in regular expressions cause a SyntaxWarning instead of a DeprecationWarning.
Solution:
- Use raw string syntax for regular expressions in Python.
> :bug: Fix python regexes

- test/log/catalog1_lib.cpp
- test/log/catalog_app.cpp
- test/log/stable_strings.json
- tools/gen_str_catalog.py
> :sparkles: Allow string catalog generation to use stable module IDs

- docs/message.adoc
- include/log/catalog/mipi_encoder.hpp
- include/msg/field.hpp
- include/msg/field_matchers.hpp
- include/msg/message.hpp
- test/CMakeLists.txt
- test/msg/callback.cpp
- test/msg/fail/impossible_match_callback.cpp
- test/msg/fail/impossible_match_field.cpp
- test/msg/fail/message_const_field_write.cpp
- test/msg/fail/message_incompatible_matcher.cpp
- test/msg/fail/message_uninitialized_field.cpp
- test/msg/handler.cpp
- test/msg/handler_builder.cpp
- test/msg/indexed_builder.cpp
- test/msg/indexed_callback.cpp
- test/msg/message.cpp
- test/msg/rle_indexed_builder.cpp
- Make field matcher aliases snake_case
- Preserve legacy field matcher aliases for now
- Add field default aliases
- Compile-time error when messages are constructed with uninitialized fields
Closes #551
> :art: Rework field matchers/default values

- test/CMakeLists.txt
The pseudo pext code needs more help; I can't even build it yet (tried clang 17, 18, gcc 13).
I've started making a task list in issue https://github.com/intel/compile-time-init-build/issues/561
> :bug: Fix up cmake for pseudo pext benchmarks

- include/msg/callback.hpp
- test/msg/handler.cpp
- test/msg/handler_builder.cpp
- test/msg/indexed_builder.cpp
Previous versions of message callback handler construction would deduce the `ExtraArgs` from the callable passed in by the user when forming the callback. This is no longer the case which means that the signature of `msg::callback::handle` does not match the signature of the contained `callable`.
This PR works around the issue; however, the real question is, "do we want to deduce the `ExtraArgs` from the user's handler? Deducing has some real problems because the handler is not always concrete (e.g. a generic lambda). I think the PR solution is probably the correct route.
> msg::callback::handle args determined by caller

- include/msg/message.hpp
Catches cases of accidental dangling, e.g.:
```cpp
auto v = msg{/* fields*/}.as_const_view();
```
> :children_crossing: Add LIFETIMEBOUND annotations for message views

- docs/logging.adoc
- include/log/log.hpp
- include/sc/format.hpp
- test/log/fmt_logger.cpp
I decided to call them "flavoured" rather than "coloured" to avoid confusion with colour in log output.
> :sparkles: Add capability for flavored (e.g. secure) logs

- docs/message.adoc
- include/msg/message.hpp
- test/CMakeLists.txt
- test/msg/fail/message_cmp_owner.cpp
- test/msg/fail/message_cmp_view.cpp
- test/msg/message.cpp
Problem:
- equality is not defined for span, so it is also not defined for messages.
Solution:
- add `msg::equivalent` to determine whether two message instances are
equivalent (all fields have the same values).
- equivalence is defined for all combinations of owning, const and mutable view
types.
> :sparkles: Add message equivalence

- .github/workflows/unit_tests.yml
Temporarily disable GCC sanitizers.
> :construction_worker: :arrow_up: Bump valgrind to use GCC 13

- include/flow/step.hpp
- include/msg/message.hpp
GCC and clang allow a user-defined literal operator template with the signature:
```cpp
template <typename T, T...> auto operator""_udl();
```
This is a non-standard extension and for our purposes at least it is replaced in C++20 by using an operator template with a structural NTTP:
```cpp
template <ct_string S> auto operator""_udl();
```
> :art: Don't use nonstandard UDL extension

- .github/workflows/unit_tests.yml
- include/flow/graph_builder.hpp
- test/CMakeLists.txt
- test/flow/fail/cyclic_flow.cpp
The error trace given is something like:
```
/.../include/flow/graph_builder.hpp:150:27: fatal error: static assertion failed due to requirement 'built.has_value()': Topological so
rt failed: cycle in flow
150 |             static_assert(built.has_value(),
|                           ^~~~~~~~~~~~~~~~~
/.../include/flow/graph_builder.hpp:155:39: note: in instantiation of member function 'flow::graph_builder<flow::impl>::built_flow<cib:
:initialized<(anonymous namespace)::CyclicFlowConfig, (anonymous namespace)::TestFlowAlpha>>::built' requested here
155 |         constexpr static auto run() { built()(); }
|                                       ^
/.../include/flow/graph_builder.hpp:160:53: note: in instantiation of member function 'flow::graph_builder<flow::impl>::built_flow<cib: …
```
> :children_crossing: Improve error message for cyclic flows

- include/msg/message.hpp
- test/msg/message.cpp
Problem:
There is no example way to test message equivalence.
Solution:
Provide a test that implements a Catch2 matcher. A similar concept exists for GoogleTest.
> :white_check_mark: Add message equivalence matcher for Catch2

- CMakeLists.txt
- include/cib/callback.hpp
- include/cib/detail/config_details.hpp
- include/cib/detail/config_item.hpp
- include/cib/detail/exports.hpp
- include/cib/detail/extend.hpp
- include/cib/detail/nexus_details.hpp
The change to use `gather_by` provides a good speedup; a few other things provide small speedups.
> :zap: Improve compilation benchmark

- include/cib/callback.hpp
- include/flow/graph_builder.hpp
- include/flow/graphviz_builder.hpp
- include/log/catalog/mipi_encoder.hpp
- include/msg/message.hpp
- include/sc/lazy_string_format.hpp
Updates to clang-tidy mean that some old directives are no longer needed.
> :rotating_light: Remove some old lint directives

- include/msg/field.hpp
- test/msg/field_insert.cpp
A field's type can be larger than the bits used in the message. It is sometimes useful at runtime to determine whether or not a given value will fit in a field.
> :sparkles: Add `can_hold` to `field`

- include/msg/detail/indexed_builder_common.hpp
- include/msg/detail/indexed_handler_common.hpp
- test/msg/indexed_builder.cpp
- test/msg/indexed_handler.cpp
An indexed handler may have indexed callbacks to call, but those callbacks may not handle the message, because they have extra matchers that weren't part of the index.
> :bug: Fix return value of `indexed_handler::handle`

- include/msg/handler.hpp
- test/msg/handler.cpp
The handler should call all the callbacks that match a message, not just the first that matches.
This is consistent with the indexed_handler behaviour.
NOTE: The order of calling the callbacks is not defined.
> :bug: Fix handler short-circuiting

- docs/flows.adoc
- examples/flow_daily_routine/main.cpp
- include/cib/config.hpp
- include/cib/detail/runtime_conditional.hpp
- include/flow/builder.hpp
- include/flow/detail/par.hpp
- include/flow/detail/seq.hpp
- include/flow/detail/walk.hpp
- include/flow/graph_builder.hpp
- include/flow/step.hpp
- include/flow/subgraph_identity.hpp
- include/match/predicate.hpp
- include/msg/callback.hpp
- include/seq/builder.hpp
- include/seq/step.hpp
- test/flow/fail/CMakeLists.txt
- test/flow/fail/mismatched_flow_runtime_conditional.cpp
- test/flow/fail/node_explicitly_added_twice.cpp
- test/flow/fail/only_reference_added.cpp
- test/flow/flow.cpp
- test/flow/graph.cpp
- test/flow/graph_builder.cpp
- test/msg/handler_builder.cpp
- test/msg/indexed_builder.cpp
- test/seq/sequencer.cpp
TODO:
- ✅Better way to ensure predicates for the same condition are unique
- ✅operator&& for predicates
- ✅Better error message for edge/node predicate requirements
- ✅Documentation
- ✅More unit tests for edge/node predicate requirements
- ✅unary operator* for seq/par objects 
- ~~unary operator- for explicit references (can't be made into non-reference by unary +)~~
- ✅Message handler support
- ✅Indexed message handler tests
- ~~runtime_condition support for cib::callback~~ (do in follow-on PR)
> add runtime_conditional and flow unary operator*

- include/msg/callback.hpp
- include/msg/message.hpp
- test/msg/callback.cpp
Messages under a certain size are fine to copy and pass in registers.
> :art: Allow messages to be handled by value

- include/msg/detail/indexed_builder_common.hpp
- include/msg/detail/indexed_handler_common.hpp
- include/msg/handler.hpp
- include/msg/handler_builder.hpp
- include/msg/handler_interface.hpp
- include/msg/indexed_builder.hpp
- include/msg/indexed_handler.hpp
- include/msg/indexed_service.hpp
- include/msg/message.hpp
- include/msg/service.hpp
- test/msg/indexed_builder.cpp
- test/msg/indexed_handler.cpp
- remove the `T` suffix from several template arguments
- rename `BaseMsg` to `MsgBase` where appropriate: there was a mix of uses, and it isn't necessarily a message at all, but the raw storage underlying. So it's not a base message, but it is a message base.
- handle by-value callbacks in the indexed builder/handler.
> :art: Allow indexed handler to handle messages by value

- include/flow/graph_builder.hpp
- include/flow/impl.hpp
- include/seq/impl.hpp
Problem:
- The span constructor used for constructing a flow impl triggers the warning `-Wunsafe-buffer-usage-in-container`.
Solution:
- We know the exact size, so the span's extent can be typed. This also means that a runtime check is unnecessary.
> :art: Improve span for flow construction

- docs/flows.adoc
> :books: :bug: Escape the star operator

- include/lookup/lookup.hpp
- include/lookup/pseudo_pext_lookup.hpp
- test/lookup/pseudo_pext_lookup.cpp
While adding random tests to the lookup library I found a couple of bugs. Making the fix here along with tests that hit the failing scenarios.
> Fix two bugs related to pseudo pext indirect lookup with search

- CMakeLists.txt
- include/flow/graph_builder.hpp
- test/flow/fail/CMakeLists.txt
- test/flow/fail/mismatched_flow_runtime_conditional.cpp
- test/flow/fail/node_explicitly_added_twice.cpp
- test/flow/fail/only_reference_added.cpp
Problem:
- Flow errors use a hacky technique to output useful information.
Solution:
- Use `STATIC_ASSERT`.
> :art: Improve flow error messages with `STATIC_ASSERT`

- include/flow/impl.hpp
Problem:
- `flow/impl.hpp` references `flow::get_log_spec` but does not include `flow/log.hpp`.
Solution:
- Add the include.
> :bug: Add missing include to `flow/impl.hpp`

- include/flow/graph_builder.hpp
- include/flow/impl.hpp
Problem:
- Now that built flow steps have been refactored to have access to the right compile-time information, there's no need to have separate `run` and `log` functions.
Solution:
- Collapse built flow steps so that one function logs the step and runs it.
> :art: Collapse flow step run/log functions

- README.md
- USER_GUIDE.md
- benchmark/big_nexus.cpp
- examples/cib_serial_port/main.cpp
- examples/flow_daily_routine/main.cpp
- examples/hello_world/README.md
- examples/hello_world/core.hpp
- include/cib/builder_meta.hpp
- include/cib/callback.hpp
- test/cib/callback.cpp
- test/cib/nexus.cpp
- test/cib/readme_hello_world.cpp
- test/msg/indexed_builder.cpp
Problem:
- `flow` constructs are called `flow::builder` and `flow::service`.
- `callback` constructs are called `cib::callback` and `cib::callback_meta`, which is confusing.
Solution:
- Rename the `callback` constructs to `callback::builder` and `callback::service` to match the `flow` pattern.
> :art: :boom: Apply consistent naming between callback and flow

- CMakeLists.txt
This version fixes an issue with `stdx::ct_string` and `std::string_view` construction.
> :arrow_up: Update stdx version

- include/lookup/input.hpp
- test/lookup/input.cpp
Problem:
- `lookup::input` takes an `auto` template parameter.
- Platform-specific definitions of `std::size_t` make it awkward to ensure instantiations of `lookup::input` with the same size are in fact the same type.
Solution:
- fix the type of the `lookup::input` template parameter to `std::size_t`
> :bug: Fix `size_t` handling in `lookup::input`

- CMakeLists.txt
This update fixes the handling of `std::array` inside the cx containers.
> :arrow_up: Update `stdx`

- CMakeLists.txt
Integrate recent commits from https://github.com/intel/cpp-std-extensions
```
2435169 | * :fire: Remove AppleClang missing braces warning
32c9bce | * :arrow_up: Update CPM to v0.40.2
363928c | * :sparkles: Allow `bitset` construction with enums for place_bits
ec147d5 | * :sparkles: Add `is_scoped_enum`
```
> ⬆️ Bump cpp-std-extensions to 2512bcf git sha

- include/log/catalog/mipi_encoder.hpp
- include/log/log.hpp
- test/log/log.cpp
Problem:
- `CIB_FATAL` formats the string it passes to `log`, but passes the bare arguments to `stdx::panic`.
Solution:
- Pass the formatted string to `stdx::panic`.
Note:
- There is a small improvement here to `to_message` also.
> :art: Improve CIB_FATAL

- CMakeLists.txt
- include/log/log.hpp
- include/match/concepts.hpp
- include/msg/detail/separate_sum_terms.hpp
- include/sc/fwd.hpp
- test/CMakeLists.txt
- test/cib/CMakeLists.txt
- test/flow/CMakeLists.txt
- test/interrupt/CMakeLists.txt
- test/log/CMakeLists.txt
- test/lookup/CMakeLists.txt
- test/match/CMakeLists.txt
- test/msg/CMakeLists.txt
- test/sc/CMakeLists.txt
- test/sc/format.cpp
- test/sc/string_constant.cpp
- test/seq/CMakeLists.txt
In general, CIB does not have a well-defined dependency DAG between its sublibraries; but three are able to be split off quite easily: `sc`, `match` and `interrupt`.
> Split off a few libraries

- include/cib/builder_meta.hpp
- include/cib/built.hpp
- include/cib/callback.hpp
- include/cib/nexus.hpp
- include/flow/builder.hpp
- include/msg/handler_interface.hpp
- include/msg/indexed_service.hpp
- include/msg/message.hpp
- include/msg/service.hpp
- test/cib/CMakeLists.txt
- test/cib/builder_meta.cpp
- test/cib/callback_uninit.cpp
- test/flow/CMakeLists.txt
- test/flow/flow.cpp
- test/flow/flow_uninit.cpp
- test/msg/CMakeLists.txt
- test/msg/handler_uninit.cpp
- test/msg/indexed_handler_uninit.cpp
> Protect against uninitialized services

- cmake/string_catalog.cmake
Problem:
- Users of the function may pass in qualified path names for inputs; it's not correct to simply prepend the current source directory.
Solution:
- Use `file(REAL_PATH ...)` to calculate the path, which will properly handle either a qualified path or a path relative to the current source directory.
Note:
- CMake is limited in `list(TRANSFORM ...)` to fixed functions, hence this must be done with a regular `foreach`.
> :bug: Fix path calculations for `gen_str_catalog`

- CMakeLists.txt
- cmake/string_catalog.cmake
- test/log/CMakeLists.txt
Problem:
- It's awkward for a caller of `gen_str_catalog()` to supply the path to `gen_str_catalog.py`. CIB owns the python script; it already knows the path.
Solution:
- Cache the path to the script so that the caller can omit it.
> :art: Allow GEN_STR_CATALOG to be defaulted

- tools/gen_str_catalog.py
Problem:
- When there are no stable strings, one cannot get them from a dictionary.
Solution:
- Provide default empty lists.
> :bug: Fix handling optional stable catalog

- include/msg/field.hpp
- include/msg/message.hpp
- test/msg/CMakeLists.txt
- test/msg/message.cpp
- test/msg/relaxed_message.cpp
Problem:
- Developing message formats is onerous; we'd like the compiler to take care of packing messages until we know exactly where to put fields.
Solution:
- Add `relaxed_message` as in #664
Note:
- All auto-located fields are put after the fixed spec fields.
- Auto-located fields are sorted from largest to smallest to ease alignment.
Closes #664
> :sparkles: Add `relaxed_message`

- cmake/string_catalog.cmake
- tools/gen_str_catalog.py
Problem:
- The MIPI-SyST spec allows 7 bits for the module ID field. A codebase could accidentally exceed this limit, leading to unpredictable effects.
Solution:
- Check the max value of a module is not exceeded.
- Allow the max value to be customized so that alternative backends can provide alternative limits.
> :sparkles: Add check for module ID limit

- CMakeLists.txt
- include/cib/detail/runtime_conditional.hpp
- include/log/catalog/mipi_encoder.hpp
- include/log/env.hpp
- include/log/fmt/logger.hpp
- include/log/log.hpp
- include/log/module.hpp
- test/log/CMakeLists.txt
- test/log/catalog1_lib.cpp
- test/log/catalog2a_lib.cpp
- test/log/catalog2b_lib.cpp
- test/log/env.cpp
- test/log/mipi_encoder.cpp
- test/log/module_id.cpp
Problem:
- Logging is parameterized on many axes. Most logging systems include the level.
Some also include a module or source. Some include other parameters.
- Logging machinery should be agnostic to the parameterizations of each logging
backend. Adding extra parameters to logging macros is not scalable.
Solution:
- Expand the current logging module to the idea of a logging environment. An
environment allows compile-time scope-based arguments to be passed through the
logging machinery; logging backends can extract whichever values they can use
from the current environment.
> :sparkles: Introduce log environment

- CMakeLists.txt
- include/cib/detail/runtime_conditional.hpp
Problem:
- `stdx` added a breaking change, viz. the ct_string format result always being returned from `ct_format`.
Solution:
- Update code to deal with that.
> :arrow_up: Update stdx

- include/log/log.hpp
- test/log/log.cpp
Problem:
- Calling `CIB_FATAL` with stack variables fails because it uses a lambda to scope its action, without capturing stack variables.
Solution:
- Use the arguments outside the lambda expression.
> :bug: Fix `CIB_FATAL`

- CMakeLists.txt
- include/log/env.hpp
- test/log/env.cpp
Problem:
- `CIB_LOG_ENV` defines a current logging environment, but it doesn't introduce a scope, so defining more than one in a scope is ill-formed.
- Defining a logging environment for just one log line is verbose.
- The logging macros themselves should not get overloaded with environment gunk, even if there were a suitable way to do so.
Solution:
- Add `CIB_WITH_LOG_ENV` that allows defining a logging environment scope easily.
> :sparkles: Add `CIB_WITH_LOG_ENV`

- include/flow/impl.hpp
- include/log/catalog/mipi_encoder.hpp
- include/log/env.hpp
- include/log/fmt/logger.hpp
- include/log/level.hpp
- include/log/log.hpp
- test/flow/custom_log_levels.cpp
- test/flow/log_levels.cpp
- test/log/CMakeLists.txt
- test/log/catalog1_lib.cpp
- test/log/catalog2a_lib.cpp
- test/log/catalog2b_lib.cpp
- test/log/env.cpp
- test/log/fmt_logger.cpp
- test/log/level.cpp
- test/log/mipi_encoder.cpp
Problem:
- Many logging backends have varying ideas of what a log level is. The MIPI-SysT
spec defines two user-defined values. It would be nice to use a strongly-typed
enumeration in application code that can re-spell the `USER1` and `USER2`
values.
Solution:
- Make logging level-agnostic.
- The MIPI-SysT levels are provided for default use, but they aren't required.
> :sparkles: Allow custom log levels

- include/log/catalog/catalog.hpp
- include/log/catalog/mipi_encoder.hpp
- tools/gen_str_catalog.py
Level is not a property of a message string, it's a property of a message instance.
> :fire: Remove `level` from logging message symbols

- include/msg/field.hpp
- test/msg/relaxed_message.cpp
Problem:
- Unlocated ("relaxed") fields can't have matchers and default values easily specified.
Solution:
- Move the location aliases into `detail::field_t`; use the "builder pattern".
> :art: Allow "relaxed" fields to have defaults, matchers etc

- CMakeLists.txt
- include/log/catalog/mipi_builder.hpp
- include/log/catalog/mipi_encoder.hpp
- include/log/catalog/mipi_messages.hpp
- test/log/mipi_encoder.cpp
Problem:
- Mipi short messages do not contain anything except the string id: no module id, no severity, etc. A client may want this information, so may not want to automatically use the short message.
Solution:
- Allow the logging environment to supply a message builder for mipi.
> :sparkles: Allow overriding the mipi message type

- include/log/catalog/mipi_builder.hpp
- include/log/catalog/mipi_encoder.hpp
- include/log/log.hpp
Problem:
- The interplay of inlining and outlining is too complex. CE experiments show that the compiler does the right thing without it all.
Solution:
- Remove it all.
> :art: Remove inlining attributes from logging functions

- cmake/string_catalog.cmake
- include/log/catalog/catalog.hpp
- include/log/catalog/mipi_builder.hpp
- include/log/catalog/mipi_encoder.hpp
- test/log/catalog1_lib.cpp
- test/log/catalog2a_lib.cpp
- test/log/catalog_app.cpp
- test/log/mipi_encoder.cpp
- test/log/stable_strings.json
- tools/gen_str_catalog.py
Problem:
- All runtime arguments to logs are assumed by the mipi encoder to be `std::uint32_t`.
- In reality, the mipi spec supports 64-bit values as well. (See MIPI-SyS-T spec table 16.) In particular, logging a time value (from a `std::chrono::duration`) needs to account for 64 bits.
Solution:
- Pack integral values properly according to the spec. Anything 32 bits or less is packed as 32 bits. If it's 64-bits, it's packed that way.
- The XML output strings use the appropriate (printf-like) specifiers.
- The JSON output retains the C++ types, as does the generated C++.
Notes:
- Table 16 allows 64-bit integral values even when the catalog message subtype is *_P32.
- Floating point and pointer values are supported by MIPI but not by this code. Maybe in future, if there is a use case.
> :bug: Allow 64-bit values in MIPI arg encoding

- include/msg/detail/indexed_handler_common.hpp
- include/msg/handler.hpp
- test/msg/handler.cpp
- test/msg/handler_builder.cpp
- test/msg/indexed_builder.cpp
Problem:
- When a callback fails to match, it should be obvious if there were no callbacks considered.
Solution:
- Show the number of callbacks considered in the match error.
Note:
- For the non-indexed matcher, `log_mismatch` is called for each callback; however the absence of output when there are no callbacks still confuses folks.
> :art: Show number of callbacks considered on match failure

- CMakeLists.txt
- include/log/env.hpp
- include/msg/callback.hpp
- include/msg/detail/indexed_builder_common.hpp
- include/msg/message.hpp
- test/msg/callback.cpp
- test/msg/message.cpp
- test/msg/relaxed_message.cpp
Add (optional) compile-time attributes for messages using `stdx::env`.
Use a message environment to control logging for a callback match.
Closes #684
> Add message environments

- CMakeLists.txt
- docs/intro.adoc
- docs/logging.adoc
- docs/sc.adoc
- include/log/README.md
- include/log/catalog/builder.hpp
- include/log/catalog/encoder.hpp
- include/log/catalog/mipi_builder.hpp
- include/log/catalog/mipi_encoder.hpp
- include/log/log.hpp
- test/log/CMakeLists.txt
- test/log/catalog1_lib.cpp
- test/log/catalog2a_lib.cpp
- test/log/catalog2b_lib.cpp
- test/log/encoder.cpp
- test/log/level.cpp
- test/log/mipi_logger.cpp
Problem:
- Some clients are very sensitive to exactly how log functions are (or are not) inlined; they need to be able to replace the minimum. At the moment, changing inline characteristics for log writing involves copying the entire default logger.
- It is useful to have a binary message logger for any format, not just for MIPI-SyS-T.
Solution:
- Separate the log writer so that it can be separately controlled.
- Separate the MIPI message building entirely from the binary catalog-based logger.
> :art: Separate log writer from logger

- CMakeLists.txt
- include/msg/send.hpp
- test/msg/send.cpp
Problem:
- `msg::send` rolls its own receiver and op state. The functionality is composable using `just | incite_on`.
Solution:
- Use the tools available in `async`.
> :art: Refactor `msg::send` to use `incite_on`

- test/msg/handler_builder.cpp
- test/msg/indexed_builder.cpp
Problem:
- When multiple callbacks match a message, they should all be called. There was no test binding this behaviour for either the "normal" handler or the indexed handler.
Solution:
- Add tests that bind the behaviour.
> :white_check_mark: Add tests for msg handlers calling multiple callbacks

- include/msg/callback.hpp
- include/msg/detail/indexed_builder_common.hpp
- test/msg/indexed_builder.cpp
Problem:
- The indexed handler callback duplicates code from the regular callback `handle` function, just for the purpose of adding a little to the logged message.
Solution:
- Allow an extra string to be passed to the regular callback `handle`.
> :art: Unify message callbacks between indexed and normal handlers

- include/msg/field_matchers.hpp
- test/msg/field_matchers.cpp
Problem:
- When field matchers log their match descriptions, they coerce the field types to std::uint32_t. Logging can deal with other types now.
Solution:
- Preserve the field types. Only log hex values for integral types.
> :bug: Field matcher logs shouldn't coerce args to `std::uint32_t`

- CMakeLists.txt
- include/log/log.hpp
- test/log/log.cpp
Problem:
- `CIB_FATAL` expects log arguments to be interpolated into the format string, but there is no way to pass extra arguments along to `stdx::panic`.
Solution:
- Use the `format_result` tuple as the first argument to `stdx::panic`, and allow any further arguments passed to `CIB_FATAL` to be forwarded through.
Note:
- Splitting a tuple may be worthwhile to move to stdx in due course. Surprisingly I don't think we've had cause for it yet. And since clang backports pack indexing, when that is available we can use it without pulling in `stdx::tuple`.
> :art: Allow extra arguments to CIB_FATAL

- include/log/log.hpp
- test/log/log.cpp
Problem:
- `CIB_FATAL` can pass extra args through to `panic` but `CIB_ASSERT` cannot.
Solution:
- Allow extra args passed through `CIB_ASSERT`.
> :art: Pass extra args through `CIB_ASSERT`

- .github/workflows/unit_tests.yml
- CMakeLists.txt
- README.md
- include/cib/callback.hpp
- include/log/catalog/mipi_builder.hpp
- include/lookup/linear_search_lookup.hpp
- include/seq/step.hpp
Problem:
- clang-20 is stable and not yet used to compile this repo.
Solution:
- Add clang-20 support to CI.
> :construction_worker: Add clang-20 support

- include/msg/message.hpp
- test/msg/message.cpp
Problem:
- `field_name` is an empty type, and `field_name` assignment is an overloaded operator that returns a different type. Without making it `const`-qualified it cannot be called on template arguments.
Solution:
- `const`-qualify `field_name::operator=`.
> :bug: Make `field_name` assignment operation `const`

- include/log/catalog/catalog.hpp
- include/log/catalog/encoder.hpp
- include/log/string_id.hpp
- test/log/catalog1_lib.cpp
- test/log/catalog_app.cpp
- tools/gen_str_catalog.py
Problem:
- Some hardware expects certain string IDs. When logging, it would be useful to be able to fix string IDs in code and have the tooling understand that.
Solution:
- Add the ability to specify string IDs in the logging environment.
> :sparkles: Add fixed string IDs to logs

- include/log/catalog/mipi_builder.hpp
- test/log/encoder.cpp
Problem:
- The size of the catalog message payload is calculated incorrectly when using buffer storage. It assumes all the arguments are the same size as their MIPI packed types.
Solution:
- Calculate the size correctly using `pack_as_t` which reflects how the arguments are actually packed under the MIPI spec.
> :bug: Fix MIPI catalog builder using buffer

- .github/workflows/unit_tests.yml
- include/log/catalog/catalog.hpp
- include/log/catalog/mipi_builder.hpp
- test/log/encoder.cpp
- test/msg/gen_handler_data.py
- tools/CMakeLists.txt
- tools/benchmark/parse_bench_data.py
- tools/gen_str_catalog.py
- tools/gen_str_catalog_test.py
:art: Refactor `gen_str_catalog.py`
Problem:
- Ad-hoc data structures in `gen_str_catalog.py` are unwieldy.
- Enum lookup was broken by encoding change with `encode_32` etc.
- Quality build is not clean because some python scripts are not formatted with
black.
Solution:
- Introduction python classes for `Message` and `Module`; simplify code.
- Add some tests for `gen_str_catalog.py`.
- Fix enum lookup: include enum info inside `encode_32<T>`.
- Format stray python scripts.
> :art: Refactor `gen_str_catalog.py`

- include/log/catalog/encoder.hpp
- include/log/module_id.hpp
- test/log/catalog1_lib.cpp
- test/log/catalog_app.cpp
- tools/gen_str_catalog.py
Problem:
- String IDs can be fixed in code, but module IDs cannot. It's only a matter of time before someone asks for that.
Solution:
- Allow module IDs to be fixed in code with a `get_module_id` query.
Note:
- If a module ID is fixed in an environment, it is advisable also to provide the module string. Otherwise it will be fixing the ID of the "default" module.
> :sparkles: Add fixed module ID query to logging

- include/cib/config.hpp
- test/cib/nexus.cpp
Problem:
- `extend<callback::service>(f)` works fine when `f` is a lambda expression, but doesn't compile when `f` is a function.
Solution:
- Decay functions to function pointers to properly store them.
> :bug: Fix extending `callback::service` with a function

- docs/message.adoc
Problem:
- The docs for `field` mention the storage in 32-bit words, but this isn't really applicable to a field; it's a message thing (and is mentioned later in that context).
- Field locators may omit dword indices, but this is not documented.
- A couple of important things about field size are not documented.
Solution:
- Remove the reference to storage in the field section.
- Add a note that the max field size is 64 bits.
- Document the alternative `located` specialization.
- Note the compilation error when storage size exceeds type representation.
> :books: Clarify field documentation

- include/msg/message.hpp
Problem:
- For some unknown reason, one of the message view constructors is not marked `constexpr`.
Solution:
- Mark it `constexpr`.
- Also, make the ordering of `constexpr explicit` consistent.
> :art: Add `constexpr` to a message view constructor

- CMakeLists.txt
- include/interrupt/fwd.hpp
- include/msg/field.hpp
Problem:
- clang has a persistent regression where it ICEs with the error "trying to emit a call to an immediate function". This seems to be provoked by `consteval` UDLs.
Solution:
- When using clang, mark UDLs as `constexpr` rather than `consteval`.
> :children_crossing: Work around clang bug with `consteval` UDLs

- CMakeLists.txt
- include/log/log.hpp
- include/log/pp_map.hpp
- include/msg/callback.hpp
- test/log/encoder.cpp
- test/log/log.cpp
- test/msg/message.cpp
Problem:
- It's easy to accidentally forget to wrap compile-time values (with `CX_VALUE` or `std::ct`) for logging, and accidentally get runtime values instead.
- Even when wrapping correctly, the resulting log call site is verbose.
Solution:
- Automatically preserve compile-time values where possible.
> :children_crossing: Improve logging of compile-time values

- include/msg/message.hpp
- include/msg/message_destructure.hpp
- test/msg/message.cpp
Problem:
- It's sometimes useful to destructure messages.
Solution:
- Support the tuple protocol on (owning or view) messages.
Note:
- The field order is the canonical ordering of fields by lsb; this is not necessarily the declaration order in the message alias.
> :sparkles: Support tuple protocol on messages

- include/log/catalog/mipi_builder.hpp
- test/log/encoder.cpp
Problem:
- When logging runtime arguments whose total size is less than 2 `std::uint32_t`s, the mipi builder uses the `log_by_args` path, despite the fact that packing the arguments according to the mipi spec means they could use much more space.
Solution:
- Calculate the size based on the packed space, not the original argument size.
> :bug: Fix mipi catalog payload size calculation

- cmake/string_catalog.cmake
- test/log/CMakeLists.txt
Problem:
- The outputs produced by `gen_str_catalog` are built by a custom command but do not have an associated target, which means other targets can't depend on them.
Solution:
- Add an optional target for the `.cpp`, `.xml` and `.json` files produced by `gen_str_datalog`.
> :sparkles: Add target for string collateral

- include/log/fmt/logger.hpp
- test/log/fmt_logger.cpp
Problem:
- Runtime enumerations cannot in general be formatted by the fmt formatter, but work fine with the binary formatter.
Solution:
- Decay enumeration values to their `underlying_type` iff no `format_as` function is provided for them.
> :sparkles: Allow fmt formatter to format runtime enum values

- cmake/string_catalog.cmake
Problem:
- The target for the string catalog files depends on the generated files, but it is difficult for calling code to recover those dependencies.
Solution:
- Add the generated files as sources so that calling code can look at the `SOURCES` property.
> :sparkles: Add `SOURCES` to string catalog target

- include/flow/impl.hpp
Problem:
- Comparisons of a nonstatic function (pointer) are not constexpr according to GCC-15.
Solution:
- Make flow `run_func` `static`.
> :bug: Fix GCC-15 compilation

- CMakeLists.txt
Problem:
- `stdx` has fixes that affect CIB logging.
Solution:
- Update dependencies.
> :arrow_up: Update dependencies

- CMakeLists.txt
- include/log/catalog/encoder.hpp
- include/log/catalog/mipi_builder.hpp
- include/log/catalog/writer.hpp
- test/log/catalog1_lib.cpp
- test/log/catalog2a_lib.cpp
- test/log/catalog2b_lib.cpp
- test/log/encoder.cpp
- test/log/level.cpp
- test/log/mipi_logger.cpp
Problem:
- The writer has to be supplied in the log config; there are use cases for changing the writer in the environment. For instance this would provide an alternative, more flexible way to do secure logging.
- The hardcoded dichotomy between `log_by_args` and `log_by_buf` is annoying and a relic of the original implementation.
Solution:
- Allow the log writer to be passed in the log environment.
- Instead of `log_by_args` and `log_by_buf`, a writer should provide a function that takes the span to write. Now the callee can choose whether to make that a function template and potentially unroll the write loop, or just a function taking a dynamic span with a runtime loop.
> :art: Logging: allow writer in env, remove `log_by_{args,buf}`

- docs/message.adoc
- include/msg/field_matchers.hpp
- include/msg/message.hpp
- test/msg/message.cpp
Problem:
- After packing messages, fields may move; matchers defined before this may not extract the right values.
Solution:
- Use name resolution to extract the right value.
> :bug: Match fields by name after packing

- .github/workflows/unit_tests.yml
- docs/intro.adoc
- include/flow/step.hpp
- include/msg/field.hpp
- include/msg/indexed_builder.hpp
Problem:
- Clang 21 has been released and is not yet used by CI.
Solution:
- Add clang-21 to CI.
> :construction_worker: Add clang-21 to CI

- include/log/catalog/mipi_builder.hpp
- include/lookup/pseudo_pext_lookup.hpp
- include/lookup/strategies.hpp
- include/match/and.hpp
- include/match/or.hpp
Problem:
- CIB is not warning free with respect to -Wnrvo.
Solution:
- Add some trailing return types etc to fix warnings.
> :rotating_light: Fix warnings arising from `-Wnrvo`

- include/msg/message.hpp
- test/msg/fail/CMakeLists.txt
- test/msg/fail/message_get_nonexistent_field.cpp
- test/msg/fail/message_set_nonexistent_field.cpp
- test/msg/message.cpp
Problem:
- Messages support `get` and `set` but not a natural indexing syntax.
Solution:
- Add `operator[]` to message, so that the follow work:
```c+++
msg["a"_field] = 42;
auto x = msg["a"_field];
```
> :children_crossing: Add `operator[]` to messages

- include/log/log.hpp
- test/log/log.cpp
Problem:
- Most of the CIB logging macros allow easy use of a custom log level type, but `CIB_FATAL` does not, because the log level is injected by the `logging::detail::panic` function.
Solution:
- Lift the injection to the `CIB_FATAL` macro and lift `panic` into the `logging` namespace so that it is comparatively easy to issue a FATAL log with a custom level type.
> :art: Expose `logging::panic` for use with custom log levels

- include/log/catalog/arguments.hpp
- test/log/catalog2b_lib.cpp
- test/log/catalog_app.cpp
- test/log/catalog_enums.hpp
- test/log/encoder.cpp
- tools/gen_str_catalog.py
Problem:
- The `.cpp` file generated by `gen_str_catalog` requires headers to be supplied in order to define the enums used. If the headers are not supplied, it does not compile.
Solution:
- Export scoped enum information sufficient to forward declare enumerations. If headers are not supplied, the `.cpp` file should still compile.
Note:
- Unscoped enums cannot be forward declared.
- Enums inside anonymous namespaces cannot be forward declared.
> :art: Autodetect scoped enums in generated `.cpp` catalog file
